#pragma once
#include <Windows.h>
#include <conio.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>
#include <map>
#include <utility>
#include <algorithm>
#include <conio.h>
#include <fstream>
#include <iterator>
#include <optional>